/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Manuel
 */
public class Frm_Menu_CircuitEquations extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Menu_CircuitEquations
     */
    public Frm_Menu_CircuitEquations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btn_JS = new javax.swing.JButton();
        btn_GN = new javax.swing.JButton();
        btn_S = new javax.swing.JButton();
        btn_W = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_W1 = new javax.swing.JButton();
        btn_e = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Circuit equations menu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 179, 173));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btn_JS.setBackground(new java.awt.Color(255, 107, 26));
        btn_JS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_JS.setForeground(new java.awt.Color(102, 36, 0));
        btn_JS.setText("Resisitor");
        btn_JS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_JSActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(btn_JS, gridBagConstraints);

        btn_GN.setBackground(new java.awt.Color(255, 107, 26));
        btn_GN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_GN.setForeground(new java.awt.Color(102, 36, 0));
        btn_GN.setText("Time");
        btn_GN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(btn_GN, gridBagConstraints);

        btn_S.setBackground(new java.awt.Color(255, 107, 26));
        btn_S.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_S.setForeground(new java.awt.Color(102, 36, 0));
        btn_S.setText("Voltage");
        btn_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(btn_S, gridBagConstraints);

        btn_W.setBackground(new java.awt.Color(255, 107, 26));
        btn_W.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_W.setForeground(new java.awt.Color(102, 36, 0));
        btn_W.setText("Voltage across resistance");
        btn_W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(btn_W, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(218, 0, 55));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(179, 63, 0));
        jLabel1.setText("Circuit equations menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel1, gridBagConstraints);

        btn_W1.setBackground(new java.awt.Color(255, 107, 26));
        btn_W1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_W1.setForeground(new java.awt.Color(102, 36, 0));
        btn_W1.setText("I");
        btn_W1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_W1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(btn_W1, gridBagConstraints);

        btn_e.setBackground(new java.awt.Color(255, 107, 26));
        btn_e.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_e.setForeground(new java.awt.Color(102, 36, 0));
        btn_e.setText("Exit");
        btn_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(btn_e, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_JSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_JSActionPerformed
        // We open the form of the approximation formula according to James Striling.
        new View.CircuitEquations.Frm_R().setVisible(true);
    }//GEN-LAST:event_btn_JSActionPerformed

    private void btn_GNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GNActionPerformed
        // We open the form of the approximation formula according to Gergo Nemes:
        new View.CircuitEquations.Frm_T().setVisible(true);
    }//GEN-LAST:event_btn_GNActionPerformed

    private void btn_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SActionPerformed
        //We open the form of the approximation formula according to Srinivasa:
        new View.CircuitEquations.Frm_E().setVisible(true);
    }//GEN-LAST:event_btn_SActionPerformed

    private void btn_WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WActionPerformed
        // We open the form of the approximation formula according to Wehmeier.
        new View.CircuitEquations.Frm_Vr().setVisible(true);
    }//GEN-LAST:event_btn_WActionPerformed

    private void btn_W1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_W1ActionPerformed
        // TODO add your handling code here:
        new View.CircuitEquations.Frm_I().setVisible(true);
    }//GEN-LAST:event_btn_W1ActionPerformed

    private void btn_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_eActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_CircuitEquations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_CircuitEquations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_CircuitEquations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_CircuitEquations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Menu_CircuitEquations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GN;
    private javax.swing.JButton btn_JS;
    private javax.swing.JButton btn_S;
    private javax.swing.JButton btn_W;
    private javax.swing.JButton btn_W1;
    private javax.swing.JButton btn_e;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
