/*
 * In this program we create the form to enter and display the data for the calculation of T
Creadto: Juan Manuel Anacona 
Contact: 3204299106
Date: 9/08/2023
 */
package View.CircuitEquations;
//We import the model and the controller
import Controller.C_CircuitEquations;
import Model.M_CircuitEquations;
/**
 *
 * @author 
 */
public class Frm_T extends javax.swing.JFrame {
    //We declare the controller and model objects.
    Controller.C_CircuitEquations ObjC = new Controller.C_CircuitEquations(0,0,0,0,0,0,0,0,0,0,0,0,0);
    Model.M_CircuitEquations ObjM = new Model.M_CircuitEquations();
    /**
     * Creates new form Frm_T
     */
    public Frm_T() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_r = new javax.swing.JTextField();
        txt_c = new javax.swing.JTextField();
        txt_v = new javax.swing.JTextField();
        txt_e = new javax.swing.JTextField();
        txt_td = new javax.swing.JTextField();
        btn_C = new javax.swing.JButton();
        btn_N = new javax.swing.JButton();
        btn_E = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_tc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculate T");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 179, 173));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(179, 63, 0));
        jLabel1.setText("Enther (R):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(179, 63, 0));
        jLabel2.setText("Enther (C):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(179, 63, 0));
        jLabel3.setText("Enther (V):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(179, 63, 0));
        jLabel4.setText("Enther (E):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(179, 63, 0));
        jLabel5.setText("Dowload value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel5, gridBagConstraints);

        txt_r.setBackground(new java.awt.Color(0, 102, 99));
        txt_r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_r.setForeground(new java.awt.Color(255, 255, 255));
        txt_r.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(txt_r, gridBagConstraints);

        txt_c.setBackground(new java.awt.Color(0, 102, 99));
        txt_c.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_c.setForeground(new java.awt.Color(255, 255, 255));
        txt_c.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(txt_c, gridBagConstraints);

        txt_v.setBackground(new java.awt.Color(0, 102, 99));
        txt_v.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_v.setForeground(new java.awt.Color(255, 255, 255));
        txt_v.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(txt_v, gridBagConstraints);

        txt_e.setBackground(new java.awt.Color(0, 102, 99));
        txt_e.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_e.setForeground(new java.awt.Color(255, 255, 255));
        txt_e.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(txt_e, gridBagConstraints);

        txt_td.setBackground(new java.awt.Color(0, 102, 99));
        txt_td.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_td.setForeground(new java.awt.Color(255, 255, 255));
        txt_td.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(txt_td, gridBagConstraints);

        btn_C.setBackground(new java.awt.Color(255, 107, 26));
        btn_C.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_C.setForeground(new java.awt.Color(102, 36, 0));
        btn_C.setText("Calculate");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(btn_C, gridBagConstraints);

        btn_N.setBackground(new java.awt.Color(255, 107, 26));
        btn_N.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_N.setForeground(new java.awt.Color(102, 36, 0));
        btn_N.setText("New");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(btn_N, gridBagConstraints);

        btn_E.setBackground(new java.awt.Color(255, 107, 26));
        btn_E.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_E.setForeground(new java.awt.Color(102, 36, 0));
        btn_E.setText("Exit");
        btn_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(btn_E, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(179, 63, 0));
        jLabel6.setText("Charge value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel6, gridBagConstraints);

        txt_tc.setBackground(new java.awt.Color(0, 102, 99));
        txt_tc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tc.setForeground(new java.awt.Color(255, 255, 255));
        txt_tc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(txt_tc, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        // We extract the necessary values ​​for the calculation
        ObjC.setJA_R_47(Double.parseDouble(txt_r.getText()));
        ObjC.setJA_C_47(Double.parseDouble(txt_c.getText()));
        ObjC.setJA_V_47(Double.parseDouble(txt_v.getText()));
        ObjC.setJA_E_47(Double.parseDouble(txt_e.getText()));
        
        //We calculate the T in charge and dowload.
        ObjC.setJA_TC_47(ObjM.CalcTC(ObjC.getJA_R_47(), ObjC.getJA_C_47(), ObjC.getJA_E_47(), ObjC.getJA_V_47()));
        ObjC.setJA_TD_47(ObjM.CalcTD(ObjC.getJA_R_47(), ObjC.getJA_C_47(), ObjC.getJA_E_47(), ObjC.getJA_V_47()));
        
        txt_tc.setText(String.valueOf(ObjC.getJA_TC_47()));
        txt_td.setText(String.valueOf(ObjC.getJA_TD_47())); 
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_EActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_T().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_E;
    private javax.swing.JButton btn_N;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_c;
    private javax.swing.JTextField txt_e;
    private javax.swing.JTextField txt_r;
    private javax.swing.JTextField txt_tc;
    private javax.swing.JTextField txt_td;
    private javax.swing.JTextField txt_v;
    // End of variables declaration//GEN-END:variables
}
